# Generated by Django 2.2.6 on 2019-10-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_auto_20191016_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_age',
            field=models.IntegerField(default=18),
        ),
    ]
